# Generated by Django 4.2 on 2024-12-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSampah',
            fields=[
                ('id_jenis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(choices=[('Kertas', 'Kertas'), ('Plastik', 'Plastik'), ('Logam', 'Logam'), ('Kaca', 'Kaca')], max_length=25)),
                ('harga_sampah', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id_lokasi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lokasi', models.CharField(choices=[('RT.1', 'RT.1'), ('RT.2', 'RT.2')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('alamat', models.TextField()),
                ('no_ewallet', models.CharField(max_length=20)),
                ('jenis_ewallet', models.CharField(choices=[('Dana', 'Dana'), ('Gopay', 'Gopay'), ('Shopeepay', 'Shopeepay')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nama_user', models.CharField(max_length=50)),
                ('nama_role', models.CharField(choices=[('Admin', 'Admin'), ('Pelanggan', 'Pelanggan')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('id_lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.lokasi')),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id_tabungan', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal_update_saldo_terakhir', models.DateField()),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Setoran',
            fields=[
                ('id_setoran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_setoran', models.DateField()),
                ('berat_sampah', models.IntegerField()),
                ('id_jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.jenissampah')),
                ('id_tabungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.tabungan')),
                ('id_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id_postingan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_postingan', models.DateField()),
                ('teks', models.CharField(max_length=100)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='PenarikanTabungan',
            fields=[
                ('id_penarikan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_penarikan', models.DateField()),
                ('mutasi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_tabungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.tabungan')),
            ],
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.user'),
        ),
        migrations.CreateModel(
            name='Berteman',
            fields=[
                ('id_berteman', models.AutoField(primary_key=True, serialize=False)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teman', to='bank_sampah.pelanggan')),
                ('id_pelanggan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teman_1', to='bank_sampah.pelanggan')),
                ('id_pelanggan2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teman_2', to='bank_sampah.pelanggan')),
            ],
        ),
    ]
