# Generated by Django 4.2 on 2024-12-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_sampah', '0002_alter_pelanggan_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='bank_sampah.user'),
        ),
    ]
